Use URLs to import GPG keys for Nginx.

diff --git a/rootfs/usr/local/bin/docker-nginx-download-source b/rootfs/usr/local/bin/docker-nginx-download-source
--- a/rootfs/usr/local/bin/docker-nginx-download-source
+++ b/rootfs/usr/local/bin/docker-nginx-download-source
@@ -2,7 +2,13 @@
 
 set -e
 
-NGINX_GPG_KEYS="B0F4253373F8F6F510D42178520A9993A1C052F8"
+NGINX_GPG_KEYS="
+	https://nginx.org/keys/nginx_signing.key \
+	https://nginx.org/keys/mdounin.key \
+	https://nginx.org/keys/maxim.key \
+	https://nginx.org/keys/sb.key \
+	https://nginx.org/keys/thresh.key
+"
 
 # NGINX_VERSION is provided by the Nginx Docker image as env var
 NGINX_URL="https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz"
@@ -21,17 +27,27 @@ fi
 # GnuPG download integrity check
 GNUPGHOME="$(mktemp -d)"
 export GNUPGHOME
-for server in \
-	hkp://keyserver.ubuntu.com:80 \
-	hkp://p80.pool.sks-keyservers.net:80 \
-	hkp://keys.gnupg.net \
-	ha.pool.sks-keyservers.net  \
-	pgp.mit.edu \
-; do
-	echo "Fetching GPG key $NGINX_GPG_KEYS from $server"
-	gpg --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPG_KEYS" && found=yes && break
+for key in $NGINX_GPG_KEYS; do
+	if [ "x${key#(http|https):}" != "x$key" ]; do
+		# URL
+		echo >&2 "Fetching GPG key from $key"
+		curl -sL "$key" |\
+		gpg --import && found=yes
+	else
+		# fingerprint/ID
+		for server in \
+			hkp://keyserver.ubuntu.com:80 \
+			hkp://p80.pool.sks-keyservers.net:80 \
+			hkp://keys.gnupg.net \
+			ha.pool.sks-keyservers.net  \
+			pgp.mit.edu \
+		; do
+			echo >&2 "Fetching GPG key $key from $server"
+			gpg --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPG_KEYS" && found=yes && break
+		done
+	fi
+	test -z "$found" && echo >&2 "error: failed to fetch GPG key: $key" && exit 1
 done
-test -z "$found" && echo >&2 "error: failed to fetch GPG key $GPG_KEYS" && exit 1
 gpg --batch --verify "${filename}.asc" "${filename}"
 rm -rf "$GNUPGHOME" "${filename}.asc"
 
